<?php


/**
 * This class defines the structure of the 'CMSGroupContent' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Seg 07 Mar 2011 16:26:14 BRT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CmsgroupcontentTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CmsgroupcontentTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('CMSGroupContent');
		$this->setPhpName('Cmsgroupcontent');
		$this->setClassname('Cmsgroupcontent');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('URL', 'Url', 'VARCHAR', false, 256, null);
		$this->addColumn('TITLE', 'Title', 'VARCHAR', false, 256, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Cmspage', 'Cmspage', RelationMap::ONE_TO_MANY, array('id' => 'CMSGroupContent_id', ), 'SET NULL', null);
    $this->addRelation('Cmsmenu', 'Cmsmenu', RelationMap::ONE_TO_MANY, array('id' => 'CMSGroupContent_id', ), 'SET NULL', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // CmsgroupcontentTableMap
