<?php


/**
 * This class defines the structure of the 'GradeUnit' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Seg 07 Mar 2011 16:26:13 BRT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class GradeunitTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.GradeunitTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('GradeUnit');
		$this->setPhpName('Gradeunit');
		$this->setClassname('Gradeunit');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('HORARIO_ID', 'HorarioId', 'INTEGER', 'Horario', 'ID', false, null, null);
		$this->addForeignKey('DISCIPLINA_ID', 'DisciplinaId', 'INTEGER', 'Disciplina', 'ID', false, null, null);
		$this->addForeignKey('PROFESSOR_ID', 'ProfessorId', 'INTEGER', 'Professor', 'ID', false, null, null);
		$this->addForeignKey('PERIODO_ID', 'PeriodoId', 'INTEGER', 'Periodo', 'ID', false, null, null);
		$this->addForeignKey('LOCAL_ID', 'LocalId', 'INTEGER', 'Local', 'ID', false, null, null);
		$this->addForeignKey('WEEKDAY_ID', 'WeekdayId', 'INTEGER', 'Week', 'ID', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Horario', 'Horario', RelationMap::MANY_TO_ONE, array('horario_id' => 'id', ), 'SET NULL', null);
    $this->addRelation('Disciplina', 'Disciplina', RelationMap::MANY_TO_ONE, array('disciplina_id' => 'id', ), 'SET NULL', null);
    $this->addRelation('Professor', 'Professor', RelationMap::MANY_TO_ONE, array('professor_id' => 'id', ), 'SET NULL', null);
    $this->addRelation('Periodo', 'Periodo', RelationMap::MANY_TO_ONE, array('periodo_id' => 'id', ), 'SET NULL', null);
    $this->addRelation('Local', 'Local', RelationMap::MANY_TO_ONE, array('local_id' => 'id', ), 'SET NULL', null);
    $this->addRelation('Week', 'Week', RelationMap::MANY_TO_ONE, array('weekDay_id' => 'id', ), 'SET NULL', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // GradeunitTableMap
