<?php

/**
 * Base class that represents a row from the 'GradeUnit' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Seg 07 Mar 2011 16:26:13 BRT
 *
 * @package    lib.model.om
 */
abstract class BaseGradeunit extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        GradeunitPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the horario_id field.
	 * @var        int
	 */
	protected $horario_id;

	/**
	 * The value for the disciplina_id field.
	 * @var        int
	 */
	protected $disciplina_id;

	/**
	 * The value for the professor_id field.
	 * @var        int
	 */
	protected $professor_id;

	/**
	 * The value for the periodo_id field.
	 * @var        int
	 */
	protected $periodo_id;

	/**
	 * The value for the local_id field.
	 * @var        int
	 */
	protected $local_id;

	/**
	 * The value for the weekday_id field.
	 * @var        int
	 */
	protected $weekday_id;

	/**
	 * @var        Horario
	 */
	protected $aHorario;

	/**
	 * @var        Disciplina
	 */
	protected $aDisciplina;

	/**
	 * @var        Professor
	 */
	protected $aProfessor;

	/**
	 * @var        Periodo
	 */
	protected $aPeriodo;

	/**
	 * @var        Local
	 */
	protected $aLocal;

	/**
	 * @var        Week
	 */
	protected $aWeek;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'GradeunitPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [horario_id] column value.
	 * 
	 * @return     int
	 */
	public function getHorarioId()
	{
		return $this->horario_id;
	}

	/**
	 * Get the [disciplina_id] column value.
	 * 
	 * @return     int
	 */
	public function getDisciplinaId()
	{
		return $this->disciplina_id;
	}

	/**
	 * Get the [professor_id] column value.
	 * 
	 * @return     int
	 */
	public function getProfessorId()
	{
		return $this->professor_id;
	}

	/**
	 * Get the [periodo_id] column value.
	 * 
	 * @return     int
	 */
	public function getPeriodoId()
	{
		return $this->periodo_id;
	}

	/**
	 * Get the [local_id] column value.
	 * 
	 * @return     int
	 */
	public function getLocalId()
	{
		return $this->local_id;
	}

	/**
	 * Get the [weekday_id] column value.
	 * 
	 * @return     int
	 */
	public function getWeekdayId()
	{
		return $this->weekday_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Gradeunit The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = GradeunitPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [horario_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Gradeunit The current object (for fluent API support)
	 */
	public function setHorarioId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->horario_id !== $v) {
			$this->horario_id = $v;
			$this->modifiedColumns[] = GradeunitPeer::HORARIO_ID;
		}

		if ($this->aHorario !== null && $this->aHorario->getId() !== $v) {
			$this->aHorario = null;
		}

		return $this;
	} // setHorarioId()

	/**
	 * Set the value of [disciplina_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Gradeunit The current object (for fluent API support)
	 */
	public function setDisciplinaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->disciplina_id !== $v) {
			$this->disciplina_id = $v;
			$this->modifiedColumns[] = GradeunitPeer::DISCIPLINA_ID;
		}

		if ($this->aDisciplina !== null && $this->aDisciplina->getId() !== $v) {
			$this->aDisciplina = null;
		}

		return $this;
	} // setDisciplinaId()

	/**
	 * Set the value of [professor_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Gradeunit The current object (for fluent API support)
	 */
	public function setProfessorId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->professor_id !== $v) {
			$this->professor_id = $v;
			$this->modifiedColumns[] = GradeunitPeer::PROFESSOR_ID;
		}

		if ($this->aProfessor !== null && $this->aProfessor->getId() !== $v) {
			$this->aProfessor = null;
		}

		return $this;
	} // setProfessorId()

	/**
	 * Set the value of [periodo_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Gradeunit The current object (for fluent API support)
	 */
	public function setPeriodoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->periodo_id !== $v) {
			$this->periodo_id = $v;
			$this->modifiedColumns[] = GradeunitPeer::PERIODO_ID;
		}

		if ($this->aPeriodo !== null && $this->aPeriodo->getId() !== $v) {
			$this->aPeriodo = null;
		}

		return $this;
	} // setPeriodoId()

	/**
	 * Set the value of [local_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Gradeunit The current object (for fluent API support)
	 */
	public function setLocalId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->local_id !== $v) {
			$this->local_id = $v;
			$this->modifiedColumns[] = GradeunitPeer::LOCAL_ID;
		}

		if ($this->aLocal !== null && $this->aLocal->getId() !== $v) {
			$this->aLocal = null;
		}

		return $this;
	} // setLocalId()

	/**
	 * Set the value of [weekday_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Gradeunit The current object (for fluent API support)
	 */
	public function setWeekdayId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->weekday_id !== $v) {
			$this->weekday_id = $v;
			$this->modifiedColumns[] = GradeunitPeer::WEEKDAY_ID;
		}

		if ($this->aWeek !== null && $this->aWeek->getId() !== $v) {
			$this->aWeek = null;
		}

		return $this;
	} // setWeekdayId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->horario_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->disciplina_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->professor_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->periodo_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->local_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->weekday_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = GradeunitPeer::NUM_COLUMNS - GradeunitPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Gradeunit object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aHorario !== null && $this->horario_id !== $this->aHorario->getId()) {
			$this->aHorario = null;
		}
		if ($this->aDisciplina !== null && $this->disciplina_id !== $this->aDisciplina->getId()) {
			$this->aDisciplina = null;
		}
		if ($this->aProfessor !== null && $this->professor_id !== $this->aProfessor->getId()) {
			$this->aProfessor = null;
		}
		if ($this->aPeriodo !== null && $this->periodo_id !== $this->aPeriodo->getId()) {
			$this->aPeriodo = null;
		}
		if ($this->aLocal !== null && $this->local_id !== $this->aLocal->getId()) {
			$this->aLocal = null;
		}
		if ($this->aWeek !== null && $this->weekday_id !== $this->aWeek->getId()) {
			$this->aWeek = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(GradeunitPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = GradeunitPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aHorario = null;
			$this->aDisciplina = null;
			$this->aProfessor = null;
			$this->aPeriodo = null;
			$this->aLocal = null;
			$this->aWeek = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(GradeunitPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseGradeunit:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				GradeunitPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseGradeunit:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(GradeunitPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseGradeunit:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseGradeunit:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				GradeunitPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aHorario !== null) {
				if ($this->aHorario->isModified() || $this->aHorario->isNew()) {
					$affectedRows += $this->aHorario->save($con);
				}
				$this->setHorario($this->aHorario);
			}

			if ($this->aDisciplina !== null) {
				if ($this->aDisciplina->isModified() || $this->aDisciplina->isNew()) {
					$affectedRows += $this->aDisciplina->save($con);
				}
				$this->setDisciplina($this->aDisciplina);
			}

			if ($this->aProfessor !== null) {
				if ($this->aProfessor->isModified() || $this->aProfessor->isNew()) {
					$affectedRows += $this->aProfessor->save($con);
				}
				$this->setProfessor($this->aProfessor);
			}

			if ($this->aPeriodo !== null) {
				if ($this->aPeriodo->isModified() || $this->aPeriodo->isNew()) {
					$affectedRows += $this->aPeriodo->save($con);
				}
				$this->setPeriodo($this->aPeriodo);
			}

			if ($this->aLocal !== null) {
				if ($this->aLocal->isModified() || $this->aLocal->isNew()) {
					$affectedRows += $this->aLocal->save($con);
				}
				$this->setLocal($this->aLocal);
			}

			if ($this->aWeek !== null) {
				if ($this->aWeek->isModified() || $this->aWeek->isNew()) {
					$affectedRows += $this->aWeek->save($con);
				}
				$this->setWeek($this->aWeek);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = GradeunitPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = GradeunitPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += GradeunitPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aHorario !== null) {
				if (!$this->aHorario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aHorario->getValidationFailures());
				}
			}

			if ($this->aDisciplina !== null) {
				if (!$this->aDisciplina->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aDisciplina->getValidationFailures());
				}
			}

			if ($this->aProfessor !== null) {
				if (!$this->aProfessor->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aProfessor->getValidationFailures());
				}
			}

			if ($this->aPeriodo !== null) {
				if (!$this->aPeriodo->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPeriodo->getValidationFailures());
				}
			}

			if ($this->aLocal !== null) {
				if (!$this->aLocal->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aLocal->getValidationFailures());
				}
			}

			if ($this->aWeek !== null) {
				if (!$this->aWeek->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aWeek->getValidationFailures());
				}
			}


			if (($retval = GradeunitPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = GradeunitPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getHorarioId();
				break;
			case 2:
				return $this->getDisciplinaId();
				break;
			case 3:
				return $this->getProfessorId();
				break;
			case 4:
				return $this->getPeriodoId();
				break;
			case 5:
				return $this->getLocalId();
				break;
			case 6:
				return $this->getWeekdayId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = GradeunitPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getHorarioId(),
			$keys[2] => $this->getDisciplinaId(),
			$keys[3] => $this->getProfessorId(),
			$keys[4] => $this->getPeriodoId(),
			$keys[5] => $this->getLocalId(),
			$keys[6] => $this->getWeekdayId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = GradeunitPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setHorarioId($value);
				break;
			case 2:
				$this->setDisciplinaId($value);
				break;
			case 3:
				$this->setProfessorId($value);
				break;
			case 4:
				$this->setPeriodoId($value);
				break;
			case 5:
				$this->setLocalId($value);
				break;
			case 6:
				$this->setWeekdayId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = GradeunitPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setHorarioId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDisciplinaId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setProfessorId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setPeriodoId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setLocalId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setWeekdayId($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(GradeunitPeer::DATABASE_NAME);

		if ($this->isColumnModified(GradeunitPeer::ID)) $criteria->add(GradeunitPeer::ID, $this->id);
		if ($this->isColumnModified(GradeunitPeer::HORARIO_ID)) $criteria->add(GradeunitPeer::HORARIO_ID, $this->horario_id);
		if ($this->isColumnModified(GradeunitPeer::DISCIPLINA_ID)) $criteria->add(GradeunitPeer::DISCIPLINA_ID, $this->disciplina_id);
		if ($this->isColumnModified(GradeunitPeer::PROFESSOR_ID)) $criteria->add(GradeunitPeer::PROFESSOR_ID, $this->professor_id);
		if ($this->isColumnModified(GradeunitPeer::PERIODO_ID)) $criteria->add(GradeunitPeer::PERIODO_ID, $this->periodo_id);
		if ($this->isColumnModified(GradeunitPeer::LOCAL_ID)) $criteria->add(GradeunitPeer::LOCAL_ID, $this->local_id);
		if ($this->isColumnModified(GradeunitPeer::WEEKDAY_ID)) $criteria->add(GradeunitPeer::WEEKDAY_ID, $this->weekday_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(GradeunitPeer::DATABASE_NAME);

		$criteria->add(GradeunitPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Gradeunit (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setHorarioId($this->horario_id);

		$copyObj->setDisciplinaId($this->disciplina_id);

		$copyObj->setProfessorId($this->professor_id);

		$copyObj->setPeriodoId($this->periodo_id);

		$copyObj->setLocalId($this->local_id);

		$copyObj->setWeekdayId($this->weekday_id);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Gradeunit Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     GradeunitPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new GradeunitPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Horario object.
	 *
	 * @param      Horario $v
	 * @return     Gradeunit The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setHorario(Horario $v = null)
	{
		if ($v === null) {
			$this->setHorarioId(NULL);
		} else {
			$this->setHorarioId($v->getId());
		}

		$this->aHorario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Horario object, it will not be re-added.
		if ($v !== null) {
			$v->addGradeunit($this);
		}

		return $this;
	}


	/**
	 * Get the associated Horario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Horario The associated Horario object.
	 * @throws     PropelException
	 */
	public function getHorario(PropelPDO $con = null)
	{
		if ($this->aHorario === null && ($this->horario_id !== null)) {
			$this->aHorario = HorarioPeer::retrieveByPk($this->horario_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aHorario->addGradeunits($this);
			 */
		}
		return $this->aHorario;
	}

	/**
	 * Declares an association between this object and a Disciplina object.
	 *
	 * @param      Disciplina $v
	 * @return     Gradeunit The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setDisciplina(Disciplina $v = null)
	{
		if ($v === null) {
			$this->setDisciplinaId(NULL);
		} else {
			$this->setDisciplinaId($v->getId());
		}

		$this->aDisciplina = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Disciplina object, it will not be re-added.
		if ($v !== null) {
			$v->addGradeunit($this);
		}

		return $this;
	}


	/**
	 * Get the associated Disciplina object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Disciplina The associated Disciplina object.
	 * @throws     PropelException
	 */
	public function getDisciplina(PropelPDO $con = null)
	{
		if ($this->aDisciplina === null && ($this->disciplina_id !== null)) {
			$this->aDisciplina = DisciplinaPeer::retrieveByPk($this->disciplina_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aDisciplina->addGradeunits($this);
			 */
		}
		return $this->aDisciplina;
	}

	/**
	 * Declares an association between this object and a Professor object.
	 *
	 * @param      Professor $v
	 * @return     Gradeunit The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setProfessor(Professor $v = null)
	{
		if ($v === null) {
			$this->setProfessorId(NULL);
		} else {
			$this->setProfessorId($v->getId());
		}

		$this->aProfessor = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Professor object, it will not be re-added.
		if ($v !== null) {
			$v->addGradeunit($this);
		}

		return $this;
	}


	/**
	 * Get the associated Professor object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Professor The associated Professor object.
	 * @throws     PropelException
	 */
	public function getProfessor(PropelPDO $con = null)
	{
		if ($this->aProfessor === null && ($this->professor_id !== null)) {
			$this->aProfessor = ProfessorPeer::retrieveByPk($this->professor_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aProfessor->addGradeunits($this);
			 */
		}
		return $this->aProfessor;
	}

	/**
	 * Declares an association between this object and a Periodo object.
	 *
	 * @param      Periodo $v
	 * @return     Gradeunit The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPeriodo(Periodo $v = null)
	{
		if ($v === null) {
			$this->setPeriodoId(NULL);
		} else {
			$this->setPeriodoId($v->getId());
		}

		$this->aPeriodo = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Periodo object, it will not be re-added.
		if ($v !== null) {
			$v->addGradeunit($this);
		}

		return $this;
	}


	/**
	 * Get the associated Periodo object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Periodo The associated Periodo object.
	 * @throws     PropelException
	 */
	public function getPeriodo(PropelPDO $con = null)
	{
		if ($this->aPeriodo === null && ($this->periodo_id !== null)) {
			$this->aPeriodo = PeriodoPeer::retrieveByPk($this->periodo_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPeriodo->addGradeunits($this);
			 */
		}
		return $this->aPeriodo;
	}

	/**
	 * Declares an association between this object and a Local object.
	 *
	 * @param      Local $v
	 * @return     Gradeunit The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setLocal(Local $v = null)
	{
		if ($v === null) {
			$this->setLocalId(NULL);
		} else {
			$this->setLocalId($v->getId());
		}

		$this->aLocal = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Local object, it will not be re-added.
		if ($v !== null) {
			$v->addGradeunit($this);
		}

		return $this;
	}


	/**
	 * Get the associated Local object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Local The associated Local object.
	 * @throws     PropelException
	 */
	public function getLocal(PropelPDO $con = null)
	{
		if ($this->aLocal === null && ($this->local_id !== null)) {
			$this->aLocal = LocalPeer::retrieveByPk($this->local_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aLocal->addGradeunits($this);
			 */
		}
		return $this->aLocal;
	}

	/**
	 * Declares an association between this object and a Week object.
	 *
	 * @param      Week $v
	 * @return     Gradeunit The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setWeek(Week $v = null)
	{
		if ($v === null) {
			$this->setWeekdayId(NULL);
		} else {
			$this->setWeekdayId($v->getId());
		}

		$this->aWeek = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Week object, it will not be re-added.
		if ($v !== null) {
			$v->addGradeunit($this);
		}

		return $this;
	}


	/**
	 * Get the associated Week object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Week The associated Week object.
	 * @throws     PropelException
	 */
	public function getWeek(PropelPDO $con = null)
	{
		if ($this->aWeek === null && ($this->weekday_id !== null)) {
			$this->aWeek = WeekPeer::retrieveByPk($this->weekday_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aWeek->addGradeunits($this);
			 */
		}
		return $this->aWeek;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aHorario = null;
			$this->aDisciplina = null;
			$this->aProfessor = null;
			$this->aPeriodo = null;
			$this->aLocal = null;
			$this->aWeek = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseGradeunit:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseGradeunit::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseGradeunit
