<?php


/**
 * Skeleton subclass for representing a row from the 'content' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Feb 12 02:46:52 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Content extends BaseContent {

	/**
	 * Initializes internal state of Content object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
        public static function fixmedia($content){
            $content = str_replace('="../media', '="/parasitologia/media', $content);
            $content = str_replace('="../../media', '="/parasitologia/media', $content);
            $content = str_replace('="../../../media', '="/parasitologia/media', $content);
            return $content;
        }
        public function  __toString() {
            return $this->getContent();
        }

} // Content
