<?php


/**
 * Skeleton subclass for representing a row from the 'Disciplina' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Feb 14 19:02:09 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Disciplina extends BaseDisciplina {

	/**
	 * Initializes internal state of Disciplina object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
        public function getDescriptionR(){
            $name = $this->getDescription();
            $var = "";
            for($i = 0; $i<15; $i++)
                $var.=$name[$i];

            return $var."...";
    }


} // Disciplina
