<?php


/**
 * Skeleton subclass for performing query and update operations on the 'menu' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Feb 12 02:46:52 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MenuPeer extends BaseMenuPeer {

} // MenuPeer
